version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
     - "3000:3000"
    volumes:
     - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
     - server

  socket:
    build: ./socket
    ports:
     - "8800:8800"
    volumes:
     - ./socket/src:/app/src
    depends_on:
     - client
volumes:
  data:
  logs: